[Feat] 로컬 로그인, 회원가입
Review-zip/ReviewZip-BE pull request #118
Opened 2024-01-31 12:50 UTC by leesuyong4029

2024-01-31 15:16 UTC, hsuush reviewed
현재 작업이 진행중인 코드에 대한 리뷰 남겼습니다. 수고하셨습니다!

2024-01-31 15:16 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/global/config/jwt/JwtProvider.java
> +    }
프론트엔드에서 보낸 access token으로 본인 인증이 이루어지는 코드가 해당 부분인가요? 함수에서 사용할 userId나 email를 반환하는 함수가 있으면 좋을 거 같습니다. email이 중복 되지않는다하면 email을 사용해도 되겠지만 현재 대부분의 함수가 userId를 이용하여 유저의 정보를 접근하고 있으므로 userId를 반환하는 함수도 만들면 좋을 거 같습니다.

2024-01-31 15:16 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/global/config/jwt/JwtProvider.java
> +    }
만약 Authentication을 필요로하는 부분이 없다면 현재 코드를 수정하여 함수명을 getUserId를 한 다음 현재 반환되는 Authentication에서 userId를 직접 반환하는 함수가 되어도 좋을 거 같습니다.

2024-01-31 15:16 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/global/config/jwt/JwtProvider.java
> +    }
혹시 해당 함수를 필요로하는 부분이 있나요?

2024-02-01 00:24 UTC, hsuush reviewed
추가로 궁금한 점이 생겨 리뷰 남깁니다!

2024-02-01 00:24 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
> +        Authentication authentication = authenticationManagerBuilder.getObject().authenticate(authenticationToken);
authentication이 실행될 때 라는 부분의 실행이 궁금해요. authentication은 현재 Authentication를 타입으로 하는 객체인데 이 자체가 메소드인건가요? 이 authentication이 실행되는 부분이 어딘지 알 수 있을까요?

2024-02-01 00:24 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
> +        Authentication authentication = authenticationManagerBuilder.getObject().authenticate(authenticationToken);
또한 loadUserByUsername이 실행되면 현재 회원가입하는 User가 생성되는 건가요?

2024-02-01 00:24 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/global/config/jwt/JwtProvider.java
> +    }
아니면 accessToken 만들 때 userId를 넣어서 만드는 방법도 있을 거 같습니다. 제가 저번에 카카오 로그인 구현할 때 들은 바로는 token 생성시 userId를 넣고 생성해달라고 요청했던 것으로 기억합니다.

2024-02-01 08:26 UTC, hsuush requested changes
로컬과 소셜이 함께 이용하기 위하여 필요할 거 같은 부분입니다. 숫자를 명시해 두어 순서대로 읽어주시면 감사하겠습니다. generateToken -> login > getAuthentication 부분입니다.

2024-02-01 08:26 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/global/config/jwt/JwtProvider.java
> +                .compact();
1. 여기에 claim local인지 social인지에 대한 값을 추가하면 좋을 거 같습니다.

2024-02-01 08:26 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
> +        UsernamePasswordAuthenticationToken authenticationToken = new UsernamePasswordAuthenticationToken(loginRequestDto.getEmail(), loginRequestDto.getPassword());
2. 그러면 해당 토큰에서 해당 토큰이 local인지 social인지 확인 후 분기를 두어 각자의 함수가 돌아가도록 하면 될 거 같습니다.

2024-02-01 08:26 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/global/config/jwt/JwtProvider.java
> +    }
3. 그렇게 되면 이 유저정보 가져오는 (user id를 반환한다는 가정하에) 부분도 해당 type을 확인하여 각자의 복호화 과정을 거치면 될 거 같습니다

2024-02-01 08:53 UTC, leesuyong4029 commented on src/main/java/com/example/ReviewZIP/global/config/jwt/JwtProvider.java
> +                .compact();
넵 카카오 로그인이랑 구별하기 위해서 반영하도록 하겠습니다!

2024-02-01 09:15 UTC, leesuyong4029 commented on src/main/java/com/example/ReviewZIP/global/config/jwt/JwtProvider.java
> +    }
넵 저희가 userId를 가지고 대부분의 기능이 구현되는 만큼 이를 고려해서 코드 수정하도록 하겠습니다. 해당 코드는 Auth Server에 요청을 해서 해당 토큰을 복호화해 관련 정보를 가져오는 코드를 의미합니다.

2024-02-01 09:34 UTC, hsuush commented
그러면 함수마다 인증이 이루어질 함수 하나 생성 가능하실까요? resolveToken과 userId를 반환하는 함수를 넣어서 넣는 값은 resolveToken에 맞추고 반환은 getUserId로 해서요!

2024-02-01 09:36 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenService.java
> +        Authentication authentication = authenticationManagerBuilder.getObject().authenticate(authenticationToken);
해당 인증/인가 부분은 공부해본 적이 없어 신기하네요. 감사합니다!

2024-02-01 09:36 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/global/config/jwt/JwtProvider.java
> +    }
넵 감사합니다!

2024-02-02 05:33 UTC, yoondaeng commented
수고많으십니다 시온
로그와 제 PR 참고해서 상세히 설명도 추가해주시면 감사할거 같습니다!

2024-02-02 05:42 UTC, hsuush commented
그리고 유저생성시 status ENABLED로 넣어주시면 감사하겠습니다!

2024-02-02 07:54 UTC, leesuyong4029 commented
넵 참고해서 수정하겠습니다!

2024-02-06 10:19 UTC, closed without merging