[feat] 유저 관심장소 관련 기능
Review-zip/ReviewZip-BE pull request #167
Opened 2024-02-05 17:24 UTC by YPYP333YPYP

# 상세 구현 내용 

# 1. 특정 장소를 관심 장소로 등록 
## UserStoresService
``` java
public void createUserStores(UserStoresRequestDto.CreateUserStoresDto dto) {

        // 임의로 유저 아이디 값에 1L을 지정
        Users user = usersRepository.findById(1L).orElseThrow(()->new UsersHandler(ErrorStatus.USER_NOT_FOUND));

        UserStores userStores = UserStoresConverter.toEntity(dto);
        userStores.setUser(user);

        userStoresRepository.save(userStores);

    }
```
사용자의 입력을 바탕으로 관심 장소로 등록합니다

## UserStoresRquestDto
```java
public class UserStoresRequestDto {

    @Getter
    public static class CreateUserStoresDto {
        private String name;
        private String address;
        private Double latitude;
        private Double longitude;
    }
}
```
사용자에게 입력받는 항목은 다음과 같습니다.

# 2. 특정 유저의 관심장소 목록 가져오기
## UserStoresService
```java
 public UserStoresResponseDto.StoreInfoListDto getStoreInfo(Long userId) {
        Users user = usersRepository.findById(userId).orElseThrow(()->new UsersHandler(ErrorStatus.USER_NOT_FOUND));
        List<UserStores> userStoresList = userStoresRepository.findAllByUser(user);

        Integer storeSavedNum = userStoresList.size();
        String nickname = user.getNickname();

        return UserStoresConverter.toStoreInfoListDto(userStoresList,storeSavedNum,nickname);
    }
```
특정 유저의 ID 값으로 유저를 반환하고 유저를 바탕으로 유저의 관심장소를 List로 반환합니다.
사용자가 필요로 하는 정보를 Dto로 반환합니다.

## UserStoresResponseDto
```java
@Builder
    @Getter
    @Setter
    @AllArgsConstructor
    public static class StoreInfoDto {
        private Double latitude;
        private Double longitude;
        private String place;
        private String address;

    }

    @Builder
    @Getter
    @Setter
    @AllArgsConstructor
    public static class StoreInfoListDto {
        List<StoreInfoDto> storeInfoDtoList;
        private Integer saveNum;
        private String nickname;
    }
```
반환하는 형식은 다음과 같습니다.

# 3. 특정 좌표가 관심장소 인지 판별하는 기능
## UserStoresService
```java
public Boolean isInterestPlace (Double lat, Double lon) {
        return userStoresRepository.existsUserStoresByLatitudeAndLongitude(lat,lon);
    }
```
특정 좌표가 관심장소인지 아닌지를 판별하여 Boolean 값으로 반환합니다.

## UserStores
```java
public class UserStores {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private Users user;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String address;

    @Column(nullable = false)
    private Double longitude;

    @Column(nullable = false)
    private Double latitude;

}

```
UserStores의 경우 위도, 경도, 주소, 장소 이름, 유저의 항목을 가지고 있습니다.

## Users
```java
 @OneToMany(mappedBy = "user")
    private Set<UserStores> userStores = new HashSet<>();
```
Users 엔티티의 경우 userStores 항목을 추가하였습니다. 중복된 장소를 방지하기 위하여 Set 자료형을 사용했습니다.

2024-02-05 18:23 UTC, yoondaeng requested changes
이피 수고많으셨습니다.
몇가지 질문과 수정사항이 있으니 답변 부탁드립니다.

2024-02-05 18:23 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/userStores/dto/response/UserStoresResponseDto.java
> +    }
saveNum은 무엇을 의미하나요?
정확한 의미를 알 수 있게 변수명을 수정하면 좋을거 같습니다.
저장하는 관심장소의 번호를 이야기하는 것일까요?

2024-02-05 18:23 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresService.java
> +        Users user = usersRepository.findById(1L).orElseThrow(()->new UsersHandler(ErrorStatus.USER_NOT_FOUND));
`getById(IL)` 으로 해야하지 않아야하나 했는데 찾아보니 아래와 같은 차이점이 있다고합니다!

> findById(1L)
> - 주어진 ID에 해당하는 엔티티를 데이터베이스에서 찾아 반환 
> - 즉시 데이터베이스에 쿼리를 실행

> getById(1L)
> - 실제 엔티티를 로드하지 않고, 엔티티의 ID만 가지고 있는 가벼운 버전의 엔티티
> - 즉시 데이터베이스에 쿼리를 실행하지 않음 
> - 대신, 프록시의 데이터에 접근할 때 비로소 데이터베이스에 쿼리를 실행함

findById(1L).orElseThrow()와 같이 존재하지 않는 엔티티에 대해 즉시 예외를 발생시키니 findById를 사용하는 것이 더 적합할 것 같습니다.

2024-02-05 18:23 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresService.java
> +        Users user = usersRepository.findById(userId).orElseThrow(()->new UsersHandler(ErrorStatus.USER_NOT_FOUND));
이 부분 또한 마찬가지입니다.

2024-02-05 18:23 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +            @Parameter(name = "lon", description = "장소의 경도"),
lat, lon 등의 약어보다는 full name 그대로 써주시는 게 좋을 거 같습니다.

2024-02-05 18:23 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/store/dto/response/StoreResponseDto.java
> +        private String Nickname;
saveNum과 isSaved가 각각 무엇을 의미하는 것인지 설명부탁드립니다.

2024-02-05 18:23 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresService.java
> +public class UserStoresService {
`@Transactional(readOnly = true)`
트랜잭션 어노테이션 추가 부탁드립니다.

2024-02-05 18:23 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresService.java
> +    public void createUserStores(UserStoresRequestDto.CreateUserStoresDto dto) {
createUserStores이니 위 상단에 `@Transactional` 트랜잭션 어노테이션 추가 부탁드립니다.

2024-02-05 18:30 UTC, YPYP333YPYP commented on src/main/java/com/example/ReviewZIP/domain/userStores/dto/response/UserStoresResponseDto.java
> +    }
저장한 관심장소의 개수를 의미합니다.

2024-02-05 18:32 UTC, YPYP333YPYP commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +            @Parameter(name = "lon", description = "장소의 경도"),
네 수정하겠습니다. 근데 카카오맵 API의 반환값으로 lat lon 항목이 있어서 이런식으로 작성해봤는데 어떻게 생각하시나요??

2024-02-05 18:32 UTC, YPYP333YPYP commented on src/main/java/com/example/ReviewZIP/domain/store/dto/response/StoreResponseDto.java
> +        private String Nickname;
isSaved는 장소가 관심장소로 저장되었는지 안되었는지를 의미합니다

2024-02-05 18:34 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/store/dto/response/StoreResponseDto.java
> +        private String Nickname;
> isSaved는 장소가 관심장소로 저장되었는지 안되었는지를 의미합니다

아하 근데 왜 String type 인건가요? 
Boolean말고 String을 쓰신 이유가 궁금합니다!

2024-02-05 18:36 UTC, YPYP333YPYP commented on src/main/java/com/example/ReviewZIP/domain/store/dto/response/StoreResponseDto.java
> +        private String Nickname;
오... 이거 왜 에러가 안났죠?  Boolean 타입으로 수정해놓겠습니다

2024-02-05 18:36 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +            @Parameter(name = "lon", description = "장소의 경도"),
Parameters
latlng [LatLng](https://apis.map.kakao.com/web/documentation/#LatLng) 요런거 말씀하시는건가요? 저거 눌러서 보면

Parameters
latitude Number : 위도
longitude Number : 경도

이렇게 나와서 latitude, longitude로 쓰는게 맞다고봅니다.

2024-02-05 18:38 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/userStores/dto/response/UserStoresResponseDto.java
> +    }
`numOfSavedStores`
`savedStoresCount`
위 변수명처럼 "저장된 장소의 개수"라는 정보를 간결하게 표현하는 게 좋을 거 같습니다.

2024-02-05 18:38 UTC, YPYP333YPYP commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +            @Parameter(name = "lon", description = "장소의 경도"),
아 아뇨 지도 API의 경우 json으로 값을 반환해주는데 그때 lat와 lon이라는 줄임말을 사용해서 그렇습니다

2024-02-05 18:39 UTC, YPYP333YPYP commented on src/main/java/com/example/ReviewZIP/domain/userStores/dto/response/UserStoresResponseDto.java
> +    }
변수명이 너무 길어지지 않을까 하는데 좀 더 확실하게 명시하는게 좋겠군요

2024-02-05 18:40 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +            @Parameter(name = "lon", description = "장소의 경도"),
그럼 냅두셔도 될 것 같습니다. 스웨거 문서이니 뭐 프론트가 이해하면 됐죠 
늦은밤 수고 많으셨습니다!!

2024-02-05 18:44 UTC, YPYP333YPYP commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +            @Parameter(name = "lon", description = "장소의 경도"),
앗 감사합니다. 협업에서는 변수명 같이 사소한 것도 생각해 볼만한 거리 같습니다. 댕님도 늦은 시간이 고생하셨습니다.

2024-02-05 18:47 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/domain/user/Users.java
> +    private Set<UserStores> userStores = new HashSet<>();
HashSet 사용하는건 처음봐서 신기하네요!
게시물 작성 시 유저가 하나의 장소만 추가할 수 있으니까 HashSet을 일부러 사용한 건가요?
덕분에 새롭게 알고갑니다.

HashSet 관련된 참고자료 공유하고갑니다!
https://kadosholy.tistory.com/119

2024-02-06 13:33 UTC, hsuush requested changes
고생하셨습니다 이피. 한 번 리뷰 확인 부탁드릴게요

2024-02-06 13:33 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/userStores/dto/response/UserStoresResponseDto.java
> +
프론트에서 id를 반환해달라해서 storeId를 추가해주시면 될 거 같습니다.

2024-02-06 13:33 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +public class UserStoresController {
RequestMapping을 /user/stores로 하셨는데 이렇게 짜시는 것 보다 /v1/user-stores 가 나을 거 같습니다. 해당 객체는 UserStores 객체에 대한 컨트롤러라서 그렇게 판단하였는데 더 나은 것이 있을지는 모르겠습니다.

2024-02-06 13:33 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +    }
해당 함수는 유저 컨트롤러에 가는 것이 맞는 거 같습니다. 
나의 관심장소 목록 가져오기 v1/users/me/stores(혹은 user-stores)
특정 유저의 관심장소 목록 가져오기 v1/users/{userId}/stores(혹은 user-stores)

2024-02-06 13:48 UTC, YPYP333YPYP commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +public class UserStoresController {
저의 의도는 PostLikes의 경우에도 /post/like 형식으로 작성하였기 때문에 UserStores의 경우에도 /user/stores로 작성했습니다. 어떻게 생각하시나요 ?

2024-02-06 15:06 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +public class UserStoresController {
걔는 PostLikes 컨트롤러가 아닌 Post 컨트롤러라서 괜찮다고 생각해요!

2024-02-06 15:39 UTC, YPYP333YPYP commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +public class UserStoresController {
그러면 userStores의 내용을 store 컨트롤러에서 작성할까요 ?

2024-02-06 16:39 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/userStores/UserStoresController.java
> +public class UserStoresController {
생성이나 삭제는 보통 해당 controller에 작성하는 것이 맞긴해서 그냥 /v1/user-stores로 바꾸고 진행하시면 좋을 거 같습니다. store 컨트롤러에서는 게시글 추가시 지정될 store를 추가하는 함수만 있는 것이 좋을 거 같습니다!

2024-02-06 16:44 UTC, hsuush commented
@yoondaeng 게시글 생성시 장소 추가는 Stores 컨트롤러에서, 유저가 관심장소를 등록하는 것은 UserStores 컨트롤러에서 발생되는 거 같습니다. 이피 말씀대로라면 내가 리뷰를 달지않아도 관심장소로 등록이 가능하다하셨으므로 해당 기능은 관심장소 등록 기능으로 UserStores 테이블에 추가되고, 게시글 생성시 장소를 추가하는 것은 Stores 테이블에 추가되는 기능으로 따로 구현이 필요할 거 같습니다!

2024-02-06 17:34 UTC, yoondaeng approved these changes

2024-02-06 18:05 UTC, hsuush approved these changes
수정사항 확인했습니다 고생하셨습니다!

2024-02-06 18:10 UTC, merged