[Feat] 로그인 성공한 유저 정보 받아오기 기능 구현
Review-zip/ReviewZip-BE pull request #191
Opened 2024-02-11 07:20 UTC by leesuyong4029

# 구현 내용 
- 로그인에 성공한 유저로부터 유저정보 (특히 userId)를 추출하는 기능을 구현했습니다. 
- 로컬 회원가입, 로그인 컨트롤러 코드에 Swagger 문법을 적용했습니다. 
주요 코드는 다음과 같습니다. 
## Swagger 문법 적용 
### RefreshTokenController
```java
   @PostMapping("/local/sign-up")
    @Operation(summary = "로컬 회원가입", description = "JWT 이용해 로컬 회원가입 진행, SignUpRequestDto, SignUpResponseDto 사용")
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "COMMON200", description = "OK, 성공"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "USER401", description = "이미 존재하는 이메일입니다.", content = @Content(schema = @Schema(implementation = ApiResponse.class)))
    })
    public ApiResponse<SignUpResponseDto> signUp(@RequestBody SignUpRequestDto signUpRequestDto) {
        SignUpResponseDto savedUserDto = refreshTokenService.signUp(signUpRequestDto);
        return ApiResponse.onSuccess(savedUserDto);
    }

    @PostMapping("/local/login")
    @Operation(summary = "로컬 로그인", description = "JWT 이용해 로컬 로그인 진행")
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "COMMON200", description = "OK, 성공"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "USER403", description = "비밀번호가 잘못되었습니다.")
    })
    public ApiResponse<TokenDto> login(@RequestBody LoginRequestDto loginRequestDto) {
        return ApiResponse.onSuccess(refreshTokenService.login(loginRequestDto));
    }
```
- ApiResponse와 Swagger문법을 적용해 해당 컨트롤러 코드를 수정했습니다. 
## Postman 결과 
![image](https://github.com/Review-zip/ReviewZip-BE/assets/69045133/a61e8dc6-3f58-4565-9da6-2d2e2f1c0ecd)

```java
{
    "email": "reviewzip1234@gmail.com",
    "password": "12345"
}
{
    "isSuccess": true,
    "code": "COMMON200",
    "message": "성공입니다.",
    "result": {
        "grantType": "Bearer",
        "accessToken": "생략",
        "refreshToken": "생략"
    }
}
```
- 로그인에 성공할 경우 해당 auth 탭에 들어갑니다. 그리고 토큰 타입을 Bearer Token 타입으로 지정하고 해당 Token 칸에 발급받은 accessToken을 복사해서 넣습니다.
![image](https://github.com/Review-zip/ReviewZip-BE/assets/69045133/1b3ede1a-0457-4b97-bfa1-33ed0e12aa44)

## userId 추출 
## toLoginInfoDto
```java
   public static UserResponseDto.LoginInfoDto toLoginInfoDto(Users user) {
        return UserResponseDto.LoginInfoDto.builder()
                .email(user.getEmail())
                .name(user.getName())
                .nickname(user.getNickname())
                .userId(user.getId())
                .phoneNum(user.getPhone_num())
                .build();
    }
```
- 빌더 패턴을 사용해 해당 dto를 엔티티로 변환시켰습니다. 

##  getUserByEmail
```java
 public UserResponseDto.LoginInfoDto getUserByEmail(String email) {
        return UsersConverter.toLoginInfoDto(usersRepository.findByEmail(email).orElseThrow(() -> new UsersHandler(ErrorStatus.USER_NOT_FOUND)));
    }
```
- 이메일별로 해당 유저의 정보를 받아오는 서비스 코드입니다. 

##  getUserDetail
```java
  @GetMapping("/detail")
    @Operation(summary = "로그인 유저 정보 가져오기", description = "현재 로그인 한 유저 정보 받아오기, LoginInfoDto 사용")
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "COMMON200",description = "OK, 성공"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "USER404", description = "존재하지 않는 유저입니다.",content = @Content(schema = @Schema(implementation = ApiResponse.class))),
    })
    public ApiResponse<UserResponseDto.LoginInfoDto> getUserDetail(@AuthenticationPrincipal UserDetails user) {
        return ApiResponse.onSuccess(usersService.getUserByEmail(user.getUsername()));
    }
```
- 로그인에 성공한 유저로부터 해당 정보(email, userId, email, name, nickname, phoneNum)를 매핑시켜주는 컨트롤러 코드인 getUserDetail 메서드입니다. @AuthenticationPrincipal 어노테이션을 사용해 인증 후 로그인 객체를 가져왔습니다.해당 어노테이션을 사용하면  SecurityUtil 클래스에서 SecurityContextHolder에 저장된 인증된 객체를 가져옵니다. 스레드에 저장되기 때문에 다른 클래스에서 해당 객체를 가져올 수 있습니다. 
## Postman 결과
![image](https://github.com/Review-zip/ReviewZip-BE/assets/69045133/3d322ef2-1405-4010-aa62-ceb0f7a8ab2c)
- 해당 url로 GET 요청을 보낼 경우 사진과 같이 userId를 얻을 수 있습니다. 예시로 해당 userId를 path variable로 사용중인 api인 내 정보 가져오기 기능을 다음과 같이 테스트 할 수 있습니다.
![image](https://github.com/Review-zip/ReviewZip-BE/assets/69045133/649bdae7-7578-4dc7-b5c4-282569839e40)

- 해당 기능 이외에도 Token 패키지의 dto 패키지에서 dto마다 request와 response 기능을 구분하기 위해 해당 디렉토리를 생성했습니다.
- 이외에도 해당 디렉토리를 생성하게 되면서 바뀐 import 경로등을 수정했습니다.

2024-02-11 09:02 UTC, hsuush requested changes
고생하셨습니다. 수정사항 및 질문사항 확인 후 답변해주세요! 수고많으셨습니다.

2024-02-11 09:02 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
> +    }
'@AuthenticationPrincipal'을 사용하여 구현하셨군요! 로그인은 해보지않아 궁금한 점 몇개 여쭤보겠습니다!
1. 해당 함수는 UsersController에만 적어도 PostsController 등 다른 controller에도 적용이 되는건가요?
2. 설명에서 예시로 보여주신 것은 url에 {userId}가 들어가므로 특정 유저의 정보 가져오기를 이용하셨는데 원래는 /v1/users/me 에서 사용자 인증 후 정보를 가져와 함수를 실행시키는 것으로 알고있는데  그것은 어떻게 가능한지 궁금합니다! 
3. 각 함수는 그렇게 된다면 어떻게 수정하면 되나요?? userId를 어떻게 추출하여 Controller내 함수에서 사용하는지 궁금합니다.

2024-02-11 09:28 UTC, leesuyong4029 commented on src/main/java/com/example/ReviewZIP/domain/token/RefreshTokenController.java
> +@RequestMapping("v1/auth")
해당 내용 반영하겠습니다!

2024-02-11 09:57 UTC, YPYP333YPYP approved these changes
고생하셨습니다 ~

2024-02-12 06:56 UTC, leesuyong4029 commented on src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
> +    }
1. 네넵 다른 controller에 적용시 똑같이 @AuthenticationPrincipal을 사용해 편리하게 구현할 수 있습니다. 관련 내용 예시입니다. 참고로만 봐주세요.
```java
@GetMapping("/user/details")
public ApiResponse<?> getUserDetails(@AuthenticationPrincipal UserDetailsImpl userDetails) {
    Long userId = userDetails.getUserId();
    UserResponseDto.UserInfoDto userInfo = userService.getUserDetailsById(userId);
    return ApiResponse.onSuccess(userInfo);
}
```
2. 코드로직이 좀 복잡해질 것 같아서 일부러 따로 구현했는데 해당 내용 반영해서 원래대로 하기로 했던 내 정보 가져오기 관련 코드 수정했습니다. 
3.  1번 질문에 첨부한 해당 예시 참고하시면 될 것 같습니다. 

그리고 다시 push한 내용 중 UserDetails 인터페이스가 있는데 여기서 getUsername()이라는 메서드가 있습니다. 저는 이를 UserDetailsImpl이라는 커스텀 클래스를 만들어서 해당 인터페이스를 구현하는 형태로 코드를 작성했습니다. 여기서 getUsername() 메서드를 오버라이딩해서 해당 계정의 이메일을 리턴하는 형태로 진행했는데, 여기서 이를 사용한 이유는 스프링 시큐리티에서 사용자를 식별하기 위해서 입니다(스프링 시큐리티에서 사용자를 식별하는데 사용되는 기본정보입니다). 그러므로 getUsername()은 주로 인증 및 보안 컨텍스트에서 사용되고, getUserId()는 비즈니스 로직에서 주로 사용되는걸로 생각하시면 될 것 같습니다.

2024-02-12 07:07 UTC, merged