[Fix] 프로필 이미지 수정 API 구현
Review-zip/ReviewZip-BE pull request #216
Opened 2024-02-14 10:49 UTC by leesuyong4029

# 구현 내용
## S3Service
### deleteFile
```java
public void deleteFile(String fileUrl) {
        try {
            String fileName = fileUrl.substring(fileUrl.lastIndexOf("/") + 1);
            amazonS3Client.deleteObject(new DeleteObjectRequest(bucket, "ReviewImage/" + fileName));
        } catch (AmazonServiceException e) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "S3 파일 삭제 실패");
        }
    }
```
- 해당 fileUrl에 맞는 이미지를 삭제하는 기능입니다.

## UsersService
### updateProfileUrl
```java
  public UserRequestDto.UserProfileUrlDto updateProfileUrl(Long userId, MultipartFile image){
        Users user = usersRepository.findById(userId).orElseThrow(() -> new UsersHandler(ErrorStatus.USER_NOT_FOUND));

        if (user.getProfileUrl() != null && !user.getProfileUrl().isEmpty()) {
            s3Service.deleteFile(user.getProfileUrl());
        }

        S3Result uploadResult = s3Service.uploadFile(image);
        user.setProfileUrl(uploadResult.getFileUrl());
        usersRepository.save(user);

        return new UserRequestDto.UserProfileUrlDto(uploadResult.getFileUrl());
    }

``` 
- 프로필 이미지를 업데이트하는 서비스 코드입니다. 만약 기존에 프로필 이미지가 있을 경우 S3Service의 deleteFile 메소드를 사용해 기존 프로필 이미지를 삭제합니다. 만약 아닐 경우는 if문을 건너뛰고 바로 파일을 업로드합니다. 파일을 업로드하면 setProfileUrl 메서드를 사용해 해당 프로필 이미지에 대한 profileUrl을 수정합니다. 

## UsersController
### updateProfileUrl
```java
    @PatchMapping("me/profile")
    @Operation(summary = "프로필 이미지 수정하기 API", description = "마이페이지 프로필 수정하기, UserProfileDto 사용")
    @ApiResponses({
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "COMMON200", description = "OK, 성공"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "USER404", description = "유저가 존재하지 않습니다", content = @Content(schema = @Schema(implementation = ApiResponse.class))),
    })
    public ApiResponse<UserRequestDto.UserProfileUrlDto> updateProfileUrl(
            @AuthenticationPrincipal UserDetails user,
            @RequestPart("image") MultipartFile image,
            @RequestPart("data") UserRequestDto.UserProfileUrlDto profileUrlData){

        if(image.isEmpty()) {
            return ApiResponse.of(ErrorStatus.IMAGE_NOT_PROVIDED, null);
        }
        UserRequestDto.UserProfileUrlDto ProfileUrlDto = usersService.updateProfileUrl(usersService.getUserId(user), image);
        return ApiResponse.onSuccess(ProfileUrlDto);
    }
```
me/profile url에 대해서 patch 매핑을 하는 컨트롤러 코드입니다. @AuthenticationPrincipal UserDetails user를 통해 로그인한 유저 정보를 받아오고, MultipartFile과 Dto를 함께 요청 받기 위해서 두개 모두 @RequestPart를 이용했습니다. 여기서 'image'는 말 그대로 사용자가 업로드하려는 새 프로필 이미지 파일이고, 'data'는 JSON 형식의 텍스트 데이터를 의미합니다.

## Postman 결과
![image](https://github.com/Review-zip/ReviewZip-BE/assets/69045133/3e9ecfe5-91ec-4ddf-9535-5d9635eb01a5)

2024-02-14 12:19 UTC, yoondaeng requested changes
수정 부탁드립니다.

2024-02-14 12:19 UTC, yoondaeng commented on src/main/java/com/example/ReviewZIP/global/s3/S3Service.java
> +            String fileName = fileUrl.substring(fileUrl.lastIndexOf("/") + 1);
왜 이 부분에서 `fileUrl.lastIndexOf("/") + 1 `하는 건가요?
그리고 현재 fileName을 S3Service createFileName 함수를 사용하여 UUID로 랜덤 fileName 생성하는데 이 부분 추가하셔야할 거 같습니다.

2024-02-17 09:09 UTC, hsuush requested changes
제 이해론 imageId를 받고 그 Image 객체의 url만 매핑하면 된다고 이해하였습니다. 근데 지금 url을 받으시고 Image도 받으시는 건지 모르겠습니다! 답변 부탁드려요 고생하셨습니다.

2024-02-17 09:09 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
> +    @PatchMapping("me/profile")
가끔 수정하실 때 대시가 없어지네요. 대시가 어쩌다 지워지는건가요?? 수정 부탁드려요! url 신경써주세요

2024-02-17 09:09 UTC, hsuush commented on src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
> +            @RequestPart("data") UserRequestDto.UserProfileUrlDto profileUrlData){
이미지를 id값만 받는 걸로 알고있는데 image는 왜 받으시는지 궁금합니다! 그리고 Dto를 @RequestPart로 받으신 이유가 있으실까요??

2024-02-17 09:14 UTC, leesuyong4029 commented on src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
> +    @PatchMapping("me/profile")
url 주의하겠습니다! 해당 코드 작성하고 그 이후에 다른 코드를 제대로 이해를 해서 Image 받는 것을 바로 못 했네요. 해당 내용도 수정하겠습니다.

2024-02-17 09:16 UTC, leesuyong4029 commented on src/main/java/com/example/ReviewZIP/domain/user/UsersController.java
> +            @RequestPart("data") UserRequestDto.UserProfileUrlDto profileUrlData){
이미지 테이블 관련해서 해당 컨트롤러랑 서비스 코드에 대해서 제대로 이해를 안 한 상태에서 해당 내용을 구현해서 해당 부분을 잘못 구현했습니다. @RequestBody로 해도 되는데 실수로 @RequestPart로 push 했습니다.

2024-02-19 07:10 UTC, closed without merging